version: '3.4'

services:
  my-front-end:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
      - "3500"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  mybackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
      - "3500"
